### ISSUE TITLE
Ombi V4 - Update checker completely broken

### ISSUE THREAD

**Issue by rg9400** [Ombi-app/Ombi#3569]
**Describe the bug**
Ombi v4 constantly says there is an update available. Though it has been a bug for a long time, the actual updater itself is broken as well. 

**To Reproduce**
1. Access Ombi
2. Go to Settings

**Expected behavior**
Ombi should only say updates are available if there is a newer version. Ideally, Ombi should be able to grab the latest package and update itself. This used to work roughly 2 years ago before it broke, and hasn't been fixed since then. Hoping that V4 fixes it. If the updater is not going to be fixed, then I suggest that it is removed from the application completely to prevent confusion. 

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158] 4.0.337.0

**Comment by DougParker1992** [comment]
I'm just posting because I'd like to see this fixed at some point. I know there are other more important issues to deal with right now; I'm just hoping to satisfy the stale bot. :)

**Comment by bakerboy448** [comment]
Dupe of https://github.com/tidusjar/Ombi/issues/3683

**Comment by bakerboy448** [comment]
a quick and dirty update script

```
echo "Killing Ombi & Backing up DB"
pkill -f -9 "Ombi";
mv ombi_restart.cron ombi_restart_tmp.cron
cp -r ~/.ombi ~/.ombi_bkp;
echo "Updating Ombi"
 wget -O OmbiV4.tar.gz $(curl -s https://api.github.com/repos/tidusjar/Ombi.releases/releases | grep linux-x64.tar.gz | grep browser_download_url | head -1 | cut -d \" -f 4);
 mkdir ~/OmbiV4; tar xzvf OmbiV4.tar.gz -C ~/OmbiV4/
echo "Updated"
echo "Starting..."
 cd ~/OmbiV4/; screen -dmS Ombi ./Ombi --host http://*:28803 --storage ~/.ombi/;
cd ~/; mv ombi_restart_tmp.cron ombi_restart.cron
exit
```

**Comment by sienar1** [comment]
Still seeing this issue in 4.0.456.0. Install is on Ubuntu 18.04.4.

**Comment by douglasparker** [comment]
The update checker is still broken.

**Comment by douglasparker** [comment]
Welp, stale bot is the most annoying GitHub bot to date. :(

This is still an issue, but I can't be bothered with fighting against the stale bot any longer.

**Comment by tidusjar** [comment]
Not stale

**Comment by jamesmacwhite** [comment]
I remember auto updating working on v3 on Windows, is there intention to have this working v4 at some point?

I can see this topic is partly around the update notifications, they seem to be correct, although they are recommending pre-release versions as updates, which might not be ideal, if you only wanted stable releases.

**Comment by twanariens** [comment]
Should be fixed in the latest release V4.15.2

**Comment by bakerboy448** [comment]
> Should be fixed in the latest release V4.15.2

Got a link to the fixing commit for posterity and curiosity?

**Comment by twanariens** [comment]
I have no specific commit for it but I can show you this:

out of date Ombi:
![image](https://user-images.githubusercontent.com/34845004/159824129-f9f7c64a-8466-4ddc-8745-3c18f0c4c7ed.png)

up to date Ombi:
![image](https://user-images.githubusercontent.com/34845004/159824204-29911a9d-3970-4aec-a177-49f1afa30ba9.png)

Due bare in mind that the automatic updater is still broken and we would love some help if anyone with the expertise could help out. But for now we fixed the "Update checker" showing if there is a new release or not.
